version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gradle
    directory: /core
    schedule:
      interval: daily

  - package-ecosystem: gradle
    directory: /modules
    schedule:
      interval: daily

  - package-ecosystem: gradle
    directory: /sample-apps
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /sample-apps/maven-app
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /sample-apps/quarkus-app
    schedule:
      interval: daily