language: java
jdk:
    - oraclejdk11
services:
  - docker
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/modules-2/files/2.1/
  - $HOME/.gradle/wrapper/
script:
    - ./gradlew clean build
