title: MicroShed Testing
description: Get going on true-to-production tests without the hassle
baseurl: "/microshed-testing"
url: "" 

# Social usernames/URLs
twitter_username: andrew_guibert
github_username: aguibert
title_image: "https://microshed.org/microshed-testing/images/microshed-twitter.png"

# Build settings
markdown: kramdown
plugins:
  - github-pages

# Github pages settings
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
theme: jekyll-theme-minimal
