title: MicroShed Testing
description: >- # this means to ignore newlines until "baseurl:"
  MicroShed Testing offers a fast and simple way of writing and running true-to-production 
  integration tests for Java microservice applications. MicroShed Testing exercises your 
  containerized application from outside the container so you are testing the exact same 
  image that runs in production.
baseurl: "/microshed-testing"
url: "" 

# Social usernames/URLs
twitter_username: andrew_guibert
github_username: aguibert
title_image: "https://microshed.org/microshed-testing/images/microshed-twitter.png"

# Build settings
markdown: kramdown
plugins:
  - github-pages

# Github pages settings
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
theme: jekyll-theme-minimal
